# Generated by Django 5.2 on 2025-05-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_borrowlist_borrow_at_alter_borrowlist_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowcart',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
