# Generated by Django 5.2 on 2025-04-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowlist',
            name='is_borrowed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
