# Generated by Django 5.2 on 2025-04-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_borrowlist_is_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='borrowlist',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
